name: metaweather
description: Metaweather

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.5
  dio: ^3.0.10
  kiwi: ^2.0.0
  mockito: ^4.0.0
  flutter_bloc: ^6.0.5
  shared_preferences: ^0.5.10
  flutter_svg: ^0.19.0
  url_launcher: ^5.5.3
  intl: ^0.16.1
  custom_refresh_indicator: ^0.8.0+1
  data_connection_checker: ^0.3.4
  bloc_test: ^7.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: resources/fonts/Lato-Regular.ttf
          weight: 400
        - asset: resources/fonts/Lato-Bold.ttf
          weight: 700
